def test_vault_client_base_get_secrets_error(vault, caplog):
    vault.db = {"a": {"value": "b"}, "c": {"value": "d"}}
    vault.forbidden_get_paths = {"c"}

    assert vault.get_secrets("") == {
        "a": {"value": "b"},
        "c": {},
    }
    assert caplog.record_tuples[0] == (
        "vault_cli.client",
        40,
        "VaultForbidden: Insufficient access for interacting with the requested "
        "secret",
    )
