  void connectErr(const AsyncSocketException& ex) noexcept override {
    FAIL() << ex.what();
  }
