def test_log_artifact_gcp_presigned_url_error(databricks_artifact_repo, test_file):
    mock_credential_info = ArtifactCredentialInfo(
        signed_uri=MOCK_GCP_SIGNED_URL, type=ArtifactCredentialType.GCP_SIGNED_URL
    )
    with mock.patch(
        f"{DATABRICKS_ARTIFACT_REPOSITORY}._get_credential_infos",
        return_value=[mock_credential_info],
    ) as get_credential_infos_mock, mock.patch(
        "requests.Session.request", side_effect=MlflowException("MOCK ERROR")
    ):
        with pytest.raises(MlflowException, match="MOCK ERROR"):
            databricks_artifact_repo.log_artifact(test_file)
        get_credential_infos_mock.assert_called_with(GetCredentialsForWrite, MOCK_RUN_ID, ANY)
